# numpy
```
pip install numpy
```

In [4]:
import numpy as np

In [31]:
a = np.array([0, 1, 2, 3])   # 4x1 배열, 행렬
a

array([0, 1, 2, 3])

In [32]:
type(a)

numpy.ndarray

In [33]:
a.dtype

dtype('int32')

2차원

In [22]:
a2 = np.array([[1, 2, 3, 4], [0.1, 2.0, 3.0, 4.0]])
a2.dtype

dtype('float64')

In [23]:
a2

array([[1. , 2. , 3. , 4. ],
       [0.1, 2. , 3. , 4. ]])

속성

In [24]:
a.dtype, a2.dtype

(dtype('int32'), dtype('float64'))

In [28]:
a.shape, a1.shape, a2.shape

((4,), (5,), (2, 4))

In [37]:
a.ndim, a2.ndim

(1, 2)

np.arange()

In [38]:
arr1 = np.arange(30)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
arr1.ndim

1

np.reshape(): shape 변형

In [45]:
arr1 = np.arange(30).reshape(5, 6)   # 5x6
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [46]:
arr1.ndim

2

In [43]:
arr1 = arr1.reshape(30,)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
arr1.ndim

1

In [49]:
arr2 = np.ndarray(shape=(5,6), dtype = 'float64')
arr2

array([[7.56837516e-312, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 1.33511969e-306, 1.16097020e-028],
       [6.37112413e-067, 9.71520605e-067, 1.17633198e-047,
        5.01163173e+217, 8.37170074e-144, 7.27308380e-043],
       [7.61482487e+169, 4.97764903e-091, 1.26989122e-075,
        5.01163191e+217, 5.49419094e-143, 9.80058441e+252],
       [7.50189709e+247, 1.35617292e+248, 2.31086606e-052,
        6.54441409e-043, 1.19943615e-071, 2.18920078e-056],
       [4.69761690e-033, 5.04621361e+180, 8.37170571e-144,
        9.30350598e+199, 5.60230216e-067, 1.00078495e-306]])

In [50]:
arr2.shape, arr2.ndim

((5, 6), 2)

### 영행렬, 일행렬

In [51]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [52]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

np.random.randn()

In [54]:
arr = np.random.randn(2, 3)
arr

array([[-0.73917247,  0.61787092, -0.61682746],
       [ 1.2741419 , -1.58285845, -0.07781857]])

np.array()

In [57]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]], dtype=np.uint64)
arr1.dtype, arr1.shape

(dtype('uint64'), (2, 3))

In [60]:
arr1 = arr1.astype(np.float16)
arr1.dtype

dtype('float16')

#### 사칙연산

In [57]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]], dtype=np.float64)
arr1.dtype, arr1.shape

(dtype('uint64'), (2, 3))

In [62]:
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]], dtype=np.float64)
arr2.dtype, arr1.shape

(dtype('float64'), (2, 3))

In [63]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [64]:
arr2 - arr1

array([[6., 6., 6.],
       [6., 6., 6.]])

In [65]:
arr2 / arr1

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [66]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

## indexing

In [15]:
arr1 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15]], dtype=np.float64)
arr1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [6]:
arr1[0][3]

4.0

In [7]:
arr1[0][2:4]

array([3., 4.])

In [8]:
arr1[[1, 2]]

array([[ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [9]:
arr1[1]

array([ 6.,  7.,  8.,  9., 10.])

차원을 가진 배열로 접근

In [10]:
arr1[[1]]

array([[ 6.,  7.,  8.,  9., 10.]])

In [12]:
arr1[[1]] = np.array([0, 0, 0, 0, 0])
arr1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  0.,  0.,  0.,  0.],
       [11., 12., 13., 14., 15.]])

In [13]:
arr1[[1]] = 100
arr1

array([[  1.,   2.,   3.,   4.,   5.],
       [100., 100., 100., 100., 100.],
       [ 11.,  12.,  13.,  14.,  15.]])

In [14]:
arr1[:] = 0
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### slicing

In [15]:
arr1 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15]], dtype=np.float64)
arr1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [16]:
arr1[[0], 2:4]

array([[3., 4.]])

In [17]:
arr1[[0], :]

array([[1., 2., 3., 4., 5.]])

In [18]:
arr1[[0], [1, 2]]

array([2., 3.])

In [19]:
arr1[:, [1, 2]]

array([[ 2.,  3.],
       [ 7.,  8.],
       [12., 13.]])

### Fancy indexing

- 1) 논리 조건
- 2) 필터
- 3) ndarray 등에 일치하는 인덱스 요소

In [20]:
# index
arr = np.array([1, 2, 3, 4, 5, 6])
idx = np.array([False, True, True, False, False, True])

In [29]:
arr[[3,4]]

array([4, 5])

In [21]:
arr[idx]

array([2, 3, 6])

In [22]:
arr % 2

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [23]:
arr % 2 == 0

array([False,  True, False,  True, False,  True])

In [24]:
arr[ arr % 2 == 0 ]

array([2, 4, 6])

#### Inf, NaN
- 무한대
- Not a Number

In [30]:
np.array([0, -1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\Taehoon Choi\.conda\envs\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Taehoon Choi\.conda\envs\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0., -inf, -inf,  nan])

In [31]:
np.inf

inf

In [32]:
np.log(0)

C:\Users\Taehoon Choi\.conda\envs\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [35]:
np.array([10])

array([10])

In [36]:
data = np.array([[80, 78, 90, 93],
                [65, 87, 88, 75],
                [98, 100, 68, 80]])

print(data.sum())
print(data.mean())
print(data.max())
print(data.min())
print()

print(data.max(axis=0))
print(data.max(axis=1))
print()

index1 = np.argmax(data, axis = 0)
index2 = np.argmax(data, axis = 1)
print(index1, index2)

1002
83.5
100
65

[ 98 100  90  93]
[ 93  88 100]

[2 2 0 0] [3 2 1]


## 라텍스: markdown

$$
\sqrt[3]{x^3+y^3\over2}
$$

$$
\begin{pmatrix} 145 \\ 134 \\ 72
\end{pmatrix}
\\
\begin{pmatrix}
1500 & 1600 & 2500 \\
2400 & 2200 & 6800 \\
1300 & 1100 & 2300 \end{pmatrix}
$$

#### 기술통계 실습

### 데이터

In [39]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 
              2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])

In [40]:
len(x)  # 데이터 갯수

26

### 표본 평균

$$
\bar{x} = {1\over N}\sum_{i=1}^N x_i
$$

In [41]:
np.mean(x)  # 평균

4.8076923076923075

### 표본 분산
- (데이터와 평균간의 거리의 제곱의 평균(표준편차의 제곱?))
- 작으면 데이터가 모여있고 크면 데이터가 퍼져있다

$$
s^2 = {1\over N}\sum_{i=1}^N(x_i - \bar{x})^2
$$

In [43]:
np.var(x)   # 분산

115.23224852071006

In [44]:
np.var(x, ddof=1)   # 비편향 분산

119.84153846153846

### 표본 표준편차
- 표본 분산의 양의 제곱근
$$
s = \sqrt{s^2}
$$

In [45]:
np.std(x)  # 표준 편차

10.734628476137871

### 최댓값 최솟값

In [46]:
np.max(x)   # 최댓값

23

In [47]:
np.min(x)   # 최솟값

-24

### 중앙값(median)

In [48]:
np.median(x)   # 중앙값

5.0

### 사분위수
- 데이터를 오름차순으로 정렬했을 때 1/4, 2/4, 3/4의 위치에 있는 수

In [50]:
np.percentile(x, 0)  # 최솟값

-24.0

In [51]:
np.percentile(x, 25)  # 1/4 위치 값

0.0

In [53]:
np.percentile(x, 50)  # 2/4 위치 값

5.0

In [54]:
np.percentile(x, 75)  # 3/4 위치 값

10.0

In [55]:
np.percentile(x, 100)  # 최댓값

23.0